### PR TITLE
ocropy: small fixes

### LINKED ISSUE #35: ocropy: add parameters to override DPI meta-data
While waiting for OCR-D/core#376 as a general mechanism in core (sanctioned by spec) at some point in the future (3.0 milestone), we need a quick solution for Ocropy segmentation and recognition now (final workshop): override the meta-data density value with a parameter exposed to the user (as a last resort).

### PR DESCRIPTION
**Pull request by bertsky**
Also fixes #35

### CODE REVIEW

**Comment by bertsky** [comment]
> This pull request **introduces 1 alert** when merging [2e7531a](https://github.com/cisocrgroup/ocrd_cis/commit/2e7531aef7876abe87213132a9731baaa7acd6e4) into [4743d52](https://github.com/cisocrgroup/ocrd_cis/commit/4743d52819580c796360718aa90c9dd45c7fa037) - [view on LGTM.com](https://lgtm.com/projects/g/cisocrgroup/ocrd_cis/rev/pr-1ecbc9ae842399126c3ac80f74b5f06ab0abf5a4)
> 
> **new alerts:**
> 
>     * 1 for Variable defined multiple times

That's just non-sense. LGTM does not seem to understand the concept of a simple conditional here.

**Comment by bertsky** [comment]
The recent changes speed up the clipping processor approximately by a factor of 3.

**Comment by finkf** [comment]
I am happy to merge this.  But could you please have a look on the warnings from [lgtm](https://lgtm.com/projects/g/cisocrgroup/ocrd_cis/rev/pr-488f0c3ce94bfdd00faab7ffab2d2e7f1bf6c7b7)?

**Comment by bertsky** [comment]
> I am happy to merge this. But could you please have a look at the warnings from [lgtm](https://lgtm.com/projects/g/cisocrgroup/ocrd_cis/rev/pr-488f0c3ce94bfdd00faab7ffab2d2e7f1bf6c7b7)?

I did. One is a false alarm (see above), and for the unused imports I just added another commit (along with other fixes).

**Comment by bertsky** [comment]
> This pull request **introduces 2 alerts** when merging [f3c4d0e](https://github.com/cisocrgroup/ocrd_cis/commit/f3c4d0e38a5eff81c241fbe212f9045101dcc89e) into [4743d52](https://github.com/cisocrgroup/ocrd_cis/commit/4743d52819580c796360718aa90c9dd45c7fa037) - [view on LGTM.com](https://lgtm.com/projects/g/cisocrgroup/ocrd_cis/rev/pr-07b2bbdf2a052815f04be1c08fbe4e2a01278351)
> 
> **new alerts:**
> 
>     * 1 for Unused import
> 
>     * 1 for Variable defined multiple times

Please ignore this!

**Comment by bertsky** [comment]
Thanks!

**Pull request merged**
