### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by kba** [comment]
Autobuilding on https://hub.docker.com/r/ocrd/cis_ocrd/builds from https://github.com/kba/cis-ocrd-py and will be triggered on push and whenever base image is updated.

**Comment by finkf** [comment]
I have added a [Dockerfile](https://github.com/cisocrgroup/ocrd_cis/blob/dev/Dockerfile) to the project with the latest merge to dev

**Comment by kba** [comment]
> I have added a Dockerfile to the project with the latest merge to dev

Very nice, thank you!

```dockerfile
ENV VERSION="Mi 9. Okt 13:26:16 CEST 2019"
```

Do you generate this? It's really useful to have that information for debugging. If you're automating this somehow with git hooks or similar, I'd be interested.

Also it would be great if you could remove the `ENTRYPOINT` since it has the default set anyway and makes calling from CLI confusing.

Can you bump the requirement for Pillow from 5.4.1 to 6.2.0 as in this PR? I have had no more segfault issues with 6.2.0 and it has many improvements over 5.4.1

**Comment by finkf** [comment]
i normally just do a `M-- M-! date` to insert the output of `date` at point.

**Comment by finkf** [comment]
I'll remove the Entrypoint from the dockerfile np.  Is it OK to just delete the according line(s)?

**Comment by kba** [comment]
> Is it OK to just delete the according line(s)?

Yes

**Comment by finkf** [comment]
2594236f5f5b5b47c4389f21338e5de3d3556cbc

**Pull request closed without merging**
