### PR TITLE
many more Ocropy improvements

### PR DESCRIPTION
**Pull request by bertsky**
Note: this depends on OCR-D/core#311 and OCR-D/core#327 (which is already in [core:edge](https://github.com/OCR-D/core/tree/edge) but not merged to master and not released yet – except via [ocrd/core:edge](https://hub.docker.com/r/ocrd/core/tags) on Dockerhub). So merging probably does not make sense yet.

### CODE REVIEW

**Comment by bertsky** [comment]
@finkf I updated the requirement to `ocrd>=2.0.0a1`, which is the PyPI release line for `core:edge` as detailed above. So this can be merged now. 

Do you want me to release it on PyPI as well? (I don't see any versions there yet, also for the old package name. PyPI deployment is a requirement for many kinds of use cases / users...)

**Comment by kba** [comment]
> Do you want me to release it on PyPI as well? (I don't see any versions there yet, also for the old package name. PyPI deployment is a requirement for many kinds of use cases / users...)

I will do that now, as v0.0.5. Happy to turn the package over to you and support you if you're unfamiliar with pypi.

**Comment by kba** [comment]
https://pypi.org/project/cis-ocrd/ 🎉

**Comment by bertsky** [comment]
@finkf same offer from me. Also: I can help you rework the rest of the repo to get ready for core 1.0 / 2.0, and end up with a good `master` – if you like.

Regarding core, I have seen a significant change for post-correction after `ocrd==1.0.0b10`: the `TextEquiv.conf` attribute is no longer a `float`, but a string again. (Remember, we used to have a problem in core at that point with newer generateDS code not correctly _parsing_ string `conf` from PAGE strings into the PAGE DOM. The fix included a change on the other side, though: Now it _generates_ the DOM with `conf` as string as well. So you have to convert to float yourself to get the old behaviour on the receiving end during post-correction. For examples of how I fixed this in my repos, see [ocrd_keraslm](https://github.com/OCR-D/ocrd_keraslm/commit/ab21b1a3429f3887a3c01b1f6dca13aa684f1088) and [cor-asv-ann](https://github.com/ASVLeipzig/cor-asv-ann/commit/eb86f06d723de0aeca0251d39a3fc897404ef879). The reason behind this is generateDS does not support conversion from `simpleType` for attributes.)

And in case you do not already know: ocrd 1.0 was a bit premature, because the much needed image API fixes (which have already been around for a while) already break it. So we introduced a new branch `edge` on core and on ocrd_tesserocr until we know these can be trusted themselves. To remedy installation of these, they got pre-released under `ocrd==2.0.0a1` and `ocrd_tesserocr==0.5.0` now. I know – lots of complexity, very confusing. Sorry!

**Comment by finkf** [comment]
Yes, help would be appreciated.  I think, that I will merge this and add my changes to devel as well. 
Then we can check things and update master.

As to the TextEquiv.conf I think that non of our post-correction python code touches the confidence value, so we should be good.

**Comment by bertsky** [comment]
> Yes, help would be appreciated. I think, that I will merge this and add my changes to devel as well.
> Then we can check things and update master.

Ok, let me know when I should take a look.

> As to the TextEquiv.conf I think that non of our post-correction python code touches the confidence value, so we should be good.

Are you quite sure? It seems you are [using word confidences](https://github.com/cisocrgroup/ocrd_cis/blob/9d06ff09dbc37ab1e8c06a75d76cb10cae336916/ocrd_cis/align/cli.py#L162) the same way I was using glyph confidences. That line is going to fail after `1.0.0b10`. You will need something like
```python
conf = min([float(te0(x).conf or "1.") for x in word.region])
```

**Comment by finkf** [comment]
Yeah. You are right. I will fix this (after the merge).  So I will merge this now, and fix TextEquiv.conf afterwards. OK?

**Comment by bertsky** [comment]
Whatever suits you better. (The PR adds the `2.0.0a1` requirement, so it would be "cleaner" to add all other updates here first. But if you already have changes yourself, it's probably not worth the effort, and synchronize afterwards.)

**Comment by finkf** [comment]
Yes. I guess you are right

**Pull request merged**
