### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by finkf**
Merging dev into master.  This merge will then be tagged as 0.0.10. 
Development should the branch from master (the new default)

### CODE REVIEW

**Comment by bertsky** [comment]
Why did you close?

**Comment by finkf** [comment]
Its merged. Master is now the default branch.

**Comment by bertsky** [comment]
Oh, sorry. I was confused by GH showing this as closed (which for PRs means "cancelled").

Do you want me to tag older releases, too?

Do you want me to release on PyPI (upwards from [0.0.7](https://pypi.org/project/ocrd-cis/))?

**Comment by finkf** [comment]
> Oh, sorry. I was confused by GH showing this as closed (which for PRs means "cancelled").
I had to manually merge (don't really understand why), so I just closed it :)

> Do you want me to tag older releases, too?
> Do you want me to release on PyPI (upwards from 0.0.7)?
If you think, that it is worth the effort, I have nothing against it.

**Pull request closed without merging**
