### PR TITLE
check_page: double max page size to 20k by 20k pixels

### PR DESCRIPTION
**Pull request by kba**
@mweidling ran into this limit when processing newspapers.

### CODE REVIEW

**Comment by mweidling** [comment]
To give a little more context: These are double sided scans of a newspaper, not a single page.

**Comment by bertsky** [comment]
Sure, let's increase. These check functions merely act as a plausibilization to prevent crashes on extreme inputs (which is important as we don't have error handling in OCR-D core).

Mind though that pages as huge as that pose problems with processors like deskew and segment – complexity is polynomial in the pixel area, and we don't downsample. (I do have a branch locally which downsamples in various functions to improve speed, but sometimes this degrades quality...)

**Comment by mweidling** [comment]
> Sure, let's increase. These check functions merely act as a plausibilization to prevent crashes on extreme inputs (which is important as we don't have error handling in OCR-D core).
> 
> Mind though that pages as huge as that pose problems with processors like deskew and segment – complexity is polynomial in the pixel area, and we don't downsample. (I do have a branch locally which downsamples in various functions to improve speed, but sometimes this degrades quality...)

That's a good hint. The offending image has the dimensions 6590 x 10293, so @kba doubling the size is just taking extra precaution.

**Comment by mweidling** [comment]
> Sure, let's increase. These check functions merely act as a plausibilization to prevent crashes on extreme inputs (which is important as we don't have error handling in OCR-D core).
> 
> Mind though that pages as huge as that pose problems with processors like deskew and segment – complexity is polynomial in the pixel area, and we don't downsample. (I do have a branch locally which downsamples in various functions to improve speed, but sometimes this degrades quality...)

That's a good hint. The offending image has the dimensions 6590 x 10293, so @kba doubling the size is just taking extra precaution.

**Comment by mweidling** [comment]
Since we're all on the same page: Can this PR be merged? Or are there any points we have to discuss or document?

**Comment by bertsky** [comment]
Merged into #87 – closing

**Pull request closed without merging**
